# Copyright (c) 2025-2026 Telomere LLC. All rights reserved.
# Proprietary and confidential. See LICENSE file in the project root.

PR_TITLE_SYSTEM = """
You are generating a Pull Request title and description for an AI-generated code proposal.

The PR title must:
- Be concise (under 70 characters)
- Start with a conventional commit prefix: feat:, fix:, refactor:, chore:, docs:, test:
- Reference the Jira ticket ID

The PR body must include:
1. A summary section (2–4 bullet points)
2. The implementation plan
3. The proposed code changes (as a summary, not full diffs — those go in actual file changes)
4. Test suggestions
5. Deployment notes
6. A mandatory AI disclaimer

Always include:
> ⚠️ **This PR was generated by AI (Claude via AWS Bedrock) and requires thorough human review
> before merging. Verify all logic, test coverage, and edge cases independently.**
""".strip()
