#!/usr/bin/env python3
# Copyright (c) 2025-2026 Telomere LLC. All rights reserved.

"""
rebuild_file_summaries_simple.py
=================================
Simplified version that uses GitHub REST API directly (no MCP).
This avoids the async/MCP initialization issues.

Uses Gemini 3.1 Pro Preview for analysis.
"""

import base64
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

import requests
from pydantic import BaseModel, Field

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config.settings import settings
from llm.provider import get_llm
from langchain_core.messages import SystemMessage, HumanMessage

# Paths
REPO_MAP_FILE = Path(__file__).parent.parent / "code_intelligence" / "data" / "repo_map.txt"
OUTPUT_FILE = Path(__file__).parent.parent / "code_intelligence" / "data" / "file_summaries.json"


# ─── Pydantic Schema ────────────────────────────────────────────────────────


class FileSummary(BaseModel):
    """Comprehensive file summary generated by Gemini Pro"""

    purpose: str = Field(
        description="One sentence describing what this file does"
    )
    key_exports: list[str] = Field(
        default_factory=list,
        description="List of exported functions, classes, types, or components"
    )
    domain_concepts: list[str] = Field(
        default_factory=list,
        description="Business domain terms found in the code (e.g., 'payment', 'invoice', 'dispute')"
    )
    complexity: str = Field(
        default="medium",
        description="Code complexity: 'low', 'medium', or 'high'"
    )
    module: str = Field(
        default="general",
        description="Primary module/domain this file belongs to (e.g., 'banking', 'organizations', 'payments')"
    )
    api_routes: list[str] = Field(
        default_factory=list,
        description="API routes defined in this file (if applicable)"
    )
    prisma_models: list[str] = Field(
        default_factory=list,
        description="Prisma database models referenced (if applicable)"
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="Key external dependencies or imports"
    )


# ─── GitHub API Functions ───────────────────────────────────────────────────


def fetch_file_from_github(file_path: str) -> str | None:
    """Fetch file content from GitHub using REST API"""

    owner = settings.github_repo_owner
    repo = settings.github_repo_name
    token = settings.github_personal_access_token.get_secret_value()

    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{file_path}"

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    try:
        response = requests.get(url, headers=headers, timeout=30)

        if response.status_code == 200:
            data = response.json()

            # Decode base64 content
            content = data.get("content", "")
            if content:
                content = base64.b64decode(content).decode("utf-8", errors="replace")

                # Limit to 50KB
                if len(content) > 50000:
                    content = content[:50000]

                return content

        return None

    except Exception:
        return None


# ─── LLM Analysis ───────────────────────────────────────────────────────────


def analyze_file_with_llm(file_path: str, content: str, llm) -> dict | None:
    """Use Gemini 3.1 Pro to analyze file and extract summary"""

    if not content:
        return None

    system_prompt = """You are a senior software engineer analyzing code files.
Extract key information about this file in a structured format.

Focus on:
- What the file does (purpose)
- Exported functions, classes, types, components
- Business domain concepts (payment, organization, user, etc.)
- Code complexity (low/medium/high)
- Module/domain it belongs to
- API routes (if any)
- Database models referenced (if any)

Be concise but thorough."""

    user_prompt = f"""Analyze this file and extract structured information:

**File**: {file_path}

**Content**:
```
{content[:8000]}
```

Return a JSON object with these exact fields:
- purpose: string (one sentence)
- key_exports: array of strings (function/class/component names)
- domain_concepts: array of strings (business terms found in code)
- complexity: string ("low", "medium", or "high")
- module: string (e.g., "banking", "organizations", "payments", "admin", "auth", "email")
- api_routes: array of strings (e.g., ["/api/banking/accounts"])
- prisma_models: array of strings (e.g., ["User", "Organization"])
- dependencies: array of strings (key imports/dependencies)
"""

    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ]

        # Parse with Pydantic (timeout via signal on Unix, threading on Windows)
        import threading
        result_holder = [None]
        error_holder = [None]

        def _invoke():
            try:
                structured_llm = llm.with_structured_output(FileSummary)
                result_holder[0] = structured_llm.invoke(messages)
            except Exception as e:
                error_holder[0] = e

        thread = threading.Thread(target=_invoke, daemon=True)
        thread.start()
        thread.join(timeout=60)  # 60-second timeout per file

        if thread.is_alive():
            print(f"      LLM call timed out for {file_path}", flush=True)
            return None

        if error_holder[0]:
            raise error_holder[0]

        result = result_holder[0]

        if result:
            return {
                "path": file_path,
                "purpose": result.purpose,
                "key_exports": result.key_exports,
                "domain_concepts": result.domain_concepts,
                "complexity": result.complexity,
                "module": result.module,
                "api_routes": result.api_routes,
                "prisma_models": result.prisma_models,
                "dependencies": result.dependencies,
            }

    except Exception as e:
        print(f"      LLM analysis failed: {str(e)[:100]}", flush=True)

    return None


# ─── Main Process ───────────────────────────────────────────────────────────


def process_file(file_path: str, llm, index: int, total: int) -> dict | None:
    """Process a single file: fetch content and analyze with LLM"""

    # Fetch content from GitHub
    content = fetch_file_from_github(file_path)

    if not content:
        print(f"  [{index}/{total}] [SKIP] {file_path} - Could not fetch content", flush=True)
        return None

    # Analyze with LLM (with timeout protection)
    try:
        summary = analyze_file_with_llm(file_path, content, llm)
    except Exception as e:
        print(f"  [{index}/{total}] [ERR] {file_path} - {str(e)[:80]}", flush=True)
        return None

    if summary:
        print(f"  [{index}/{total}] [OK] {file_path} - {summary.get('module', 'general')}", flush=True)
        return summary
    else:
        print(f"  [{index}/{total}] [FAIL] {file_path} - Analysis failed", flush=True)
        return None


def rebuild_summaries():
    """Main function to rebuild file_summaries.json"""

    print("=" * 70, flush=True)
    print("Rebuilding file_summaries.json with Gemini 3.1 Pro Preview", flush=True)
    print("=" * 70, flush=True)

    # 1. Load file list from repo_map.txt
    print(f"\nChecking for {REPO_MAP_FILE}...", flush=True)
    if not REPO_MAP_FILE.exists():
        print(f"\nERROR: {REPO_MAP_FILE} not found", flush=True)
        print("Run build_repo_map_from_summaries.py first", flush=True)
        return False

    print(f"Loading file list from {REPO_MAP_FILE.name}...", flush=True)
    file_paths = []
    with open(REPO_MAP_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            # File paths don't have leading whitespace
            if line and not line.startswith(" "):
                file_paths.append(line)

    print(f"Found {len(file_paths)} total files in repo map", flush=True)

    # 2. Resume support: load existing summaries and skip already-done files
    summaries = []
    already_done = set()
    if "--resume" in sys.argv and OUTPUT_FILE.exists():
        with open(OUTPUT_FILE, encoding="utf-8") as f:
            summaries = json.load(f)
        already_done = {s["path"] for s in summaries}
        print(f"[RESUME] Loaded {len(summaries)} existing summaries, skipping those files", flush=True)

    remaining = [p for p in file_paths if p not in already_done]
    print(f"Files to process: {len(remaining)} (skipping {len(already_done)} already done)", flush=True)

    # 3. Initialize LLM
    print(f"\nInitializing Gemini 3.1 Pro Preview...", flush=True)
    print(f"Configured model: {settings.gemini_model_id}", flush=True)

    # Ensure we're using Pro model (not Flash)
    if "flash" in settings.gemini_model_id.lower():
        print("\n[WARNING] Flash model detected in .env")
        print("This script requires Gemini Pro for best quality.")
        return False

    print("Calling get_llm()...", flush=True)
    llm = get_llm()
    print("LLM initialized successfully!", flush=True)

    print(f"\n{'=' * 70}", flush=True)
    print(f"Processing {len(remaining)} files...", flush=True)
    print(f"Estimated time: ~{len(remaining) * 2 // 60} minutes", flush=True)
    print(f"{'=' * 70}\n", flush=True)

    # Process remaining files with rate limiting
    for i, file_path in enumerate(remaining):
        idx = i + 1

        result = process_file(file_path, llm, idx, len(remaining))

        if result:
            summaries.append(result)

        # Save progress every 50 files
        if idx % 50 == 0:
            print(f"\n  [SAVING] Progress checkpoint... ({len(summaries)} summaries so far)", flush=True)
            OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
                json.dump(summaries, f, indent=2)

        # Rate limiting: ~2 seconds per file
        if idx < len(remaining):
            time.sleep(1.5)

    # 3. Save final results
    print(f"\n{'=' * 70}")
    print("Saving final results...")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(summaries, f, indent=2)

    file_size = OUTPUT_FILE.stat().st_size

    print(f"\n{'=' * 70}")
    print("[SUCCESS]")
    print(f"{'=' * 70}")
    print(f"Output file: {OUTPUT_FILE}")
    print(f"File size: {file_size:,} bytes ({file_size / 1024:.1f} KB)")
    print(f"Total files processed: {len(file_paths)}")
    print(f"Successful summaries: {len(summaries)}")
    print(f"Failed: {len(file_paths) - len(summaries)}")
    print(f"{'=' * 70}")

    return True


if __name__ == "__main__":
    print("\n[WARNING] This script will take approximately 40 minutes to complete.")
    print("It will process 1104+ files with Gemini 3.1 Pro Preview.\n")

    # Check for --yes flag to skip confirmation
    if "--yes" not in sys.argv:
        response = input("Continue? (yes/no): ").strip().lower()
        if response not in ["yes", "y"]:
            print("Aborted.")
            sys.exit(0)

    success = rebuild_summaries()
    sys.exit(0 if success else 1)
