#!/usr/bin/env python3
# Copyright (c) 2025-2026 Telomere LLC. All rights reserved.

"""
rebuild_file_summaries.py
==========================
Rebuilds file_summaries.json with better, more detailed analysis using Gemini Pro.

This script:
1. Reads repo_map.txt for list of files
2. Fetches each file from GitHub
3. Uses Gemini Pro to analyze and extract:
   - Purpose and functionality
   - Key exports (functions, classes, types)
   - Domain concepts (business logic terms)
   - Complexity rating
   - Module classification
   - API routes (if applicable)
   - Prisma models (if applicable)
4. Writes enhanced file_summaries.json

Expected runtime: ~40 minutes for 1104 files
"""

import asyncio
import base64
import json
import os
import sys
from pathlib import Path
from typing import Any

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config.settings import settings
from mcp_client.client_factory import get_mcp_client, filter_github_tools
from llm.provider import get_llm
from llm.llm_logger import llm_logger
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from utils.mcp_helpers import find_tool
from utils.retry import ainvoke_with_retry
import uuid

# Paths
REPO_MAP_FILE = Path(__file__).parent.parent / "code_intelligence" / "data" / "repo_map.txt"
OUTPUT_FILE = Path(__file__).parent.parent / "code_intelligence" / "data" / "file_summaries.json"


# ─── Pydantic Schema ────────────────────────────────────────────────────────


class FileSummary(BaseModel):
    """Comprehensive file summary generated by Gemini Pro"""

    purpose: str = Field(
        description="One sentence describing what this file does"
    )
    key_exports: list[str] = Field(
        default_factory=list,
        description="List of exported functions, classes, types, or components"
    )
    domain_concepts: list[str] = Field(
        default_factory=list,
        description="Business domain terms found in the code (e.g., 'payment', 'invoice', 'dispute')"
    )
    complexity: str = Field(
        default="medium",
        description="Code complexity: 'low', 'medium', or 'high'"
    )
    module: str = Field(
        default="general",
        description="Primary module/domain this file belongs to (e.g., 'banking', 'organizations', 'payments')"
    )
    api_routes: list[str] = Field(
        default_factory=list,
        description="API routes defined in this file (if applicable)"
    )
    prisma_models: list[str] = Field(
        default_factory=list,
        description="Prisma database models referenced (if applicable)"
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="Key external dependencies or imports"
    )


# ─── Helper Functions ───────────────────────────────────────────────────────


async def fetch_file_content(tools: list, file_path: str) -> str | None:
    """Fetch file content from GitHub"""

    get_contents = find_tool(tools, "get_file_contents") or find_tool(tools, "contents")
    if not get_contents:
        return None

    owner = settings.github_repo_owner
    repo = settings.github_repo_name

    try:
        result = await ainvoke_with_retry(
            get_contents,
            {"owner": owner, "repo": repo, "path": file_path}
        )

        content = None

        # Handle MCP response format: [{"type": "text", "text": "{json}"}]
        if isinstance(result, list) and len(result) > 0:
            first_item = result[0]
            if isinstance(first_item, dict):
                if "text" in first_item:
                    text_content = first_item["text"]
                    parsed = json.loads(text_content)
                    if isinstance(parsed, dict):
                        content = parsed.get("content", "")
                        encoding = parsed.get("encoding", "")
                    else:
                        content = text_content
                elif "content" in first_item:
                    content = first_item["content"]
                    encoding = first_item.get("encoding", "")
        elif isinstance(result, dict):
            content = result.get("content", "")
            encoding = result.get("encoding", "")

        if content and encoding == "base64":
            try:
                content = base64.b64decode(content).decode("utf-8", errors="replace")
            except Exception:
                return None

        # Limit to 50KB to avoid context issues
        if content and len(content) > 50000:
            content = content[:50000]

        return content

    except Exception:
        return None


def analyze_file_with_llm(file_path: str, content: str, llm) -> dict | None:
    """Use LLM to analyze file and extract summary"""

    if not content:
        return None

    system_prompt = """You are a senior software engineer analyzing code files.
Extract key information about this file in a structured format.

Focus on:
- What the file does (purpose)
- Exported functions, classes, types, components
- Business domain concepts (payment, organization, user, etc.)
- Code complexity (low/medium/high)
- Module/domain it belongs to
- API routes (if any)
- Database models referenced (if any)

Be concise but thorough."""

    user_prompt = f"""Analyze this file and extract structured information:

**File**: {file_path}

**Content**:
```
{content[:8000]}
```

Return a JSON object with these fields:
- purpose: string (one sentence)
- key_exports: array of strings (function/class/component names)
- domain_concepts: array of strings (business terms found in code)
- complexity: string ("low", "medium", or "high")
- module: string (e.g., "banking", "organizations", "payments", "admin", "auth", "email")
- api_routes: array of strings (e.g., ["/api/banking/accounts"])
- prisma_models: array of strings (e.g., ["User", "Organization"])
- dependencies: array of strings (key imports/dependencies)
"""

    try:
        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ]

        # Use llm_logger to invoke and log
        response, record = llm_logger.invoke_and_log(
            llm=llm,
            messages=messages,
            run_id="file_summary_rebuild",
            ticket_id=file_path,
            agent_name="FileSummarizer",
            prompt_template_name="file_analysis",
            output_schema_name="FileSummary",
        )

        # Parse with Pydantic
        result = llm.with_structured_output(FileSummary).invoke(messages)

        if result:
            return {
                "path": file_path,
                "purpose": result.purpose,
                "key_exports": result.key_exports,
                "domain_concepts": result.domain_concepts,
                "complexity": result.complexity,
                "module": result.module,
                "api_routes": result.api_routes,
                "prisma_models": result.prisma_models,
                "dependencies": result.dependencies,
            }
    except Exception as e:
        print(f"      LLM analysis failed: {str(e)[:100]}")

    return None


async def process_file(
    file_path: str,
    tools: list,
    llm,
    index: int,
    total: int
) -> dict | None:
    """Process a single file: fetch content and analyze with LLM"""

    # Fetch content
    content = await fetch_file_content(tools, file_path)

    if not content:
        print(f"  [{index}/{total}] [SKIP] {file_path} - Could not fetch content")
        return None

    # Analyze with LLM (synchronous call)
    summary = analyze_file_with_llm(file_path, content, llm)

    if summary:
        print(f"  [{index}/{total}] [OK] {file_path} - {summary.get('module', 'general')}")
        return summary
    else:
        print(f"  [{index}/{total}] [FAIL] {file_path} - Analysis failed")
        return None


async def rebuild_summaries():
    """Main function to rebuild file_summaries.json"""

    print("=" * 70)
    print("Rebuilding file_summaries.json with Gemini Pro")
    print("=" * 70)

    # 1. Load file list from repo_map.txt
    if not REPO_MAP_FILE.exists():
        print(f"\nERROR: {REPO_MAP_FILE} not found")
        print("Run build_repo_map_from_summaries.py first")
        return False

    print(f"\nLoading file list from {REPO_MAP_FILE.name}...")
    file_paths = []
    with open(REPO_MAP_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            # File paths don't have leading whitespace
            if line and not line.startswith(" "):
                file_paths.append(line)

    print(f"Found {len(file_paths)} files to analyze")

    # 2. Initialize LLM and GitHub client
    print(f"\nInitializing Gemini Pro...")
    print(f"Configured model: {settings.gemini_model_id}")

    # Ensure we're using Pro model (not Flash)
    if "flash" in settings.gemini_model_id.lower():
        print("\n[WARNING] Flash model detected in .env")
        print("This script requires Gemini Pro for best quality.")
        print("Please update GEMINI_MODEL_ID in .env to a Pro model")
        return False

    llm = get_llm()  # Uses settings.gemini_model_id from .env

    print("Connecting to GitHub...")

    summaries = []

    async with get_mcp_client() as client:
        all_tools = await client.get_tools()
        gh_tools = filter_github_tools(all_tools)

        if not gh_tools:
            print("ERROR: No GitHub tools available")
            return False

        print(f"\n{'=' * 70}")
        print(f"Processing {len(file_paths)} files...")
        print(f"Estimated time: ~{len(file_paths) * 2 // 60} minutes")
        print(f"{'=' * 70}\n")

        # Process files in batches to avoid rate limits
        batch_size = 5

        for i in range(0, len(file_paths), batch_size):
            batch = file_paths[i:i+batch_size]
            batch_tasks = []

            for j, file_path in enumerate(batch):
                idx = i + j + 1
                batch_tasks.append(
                    process_file(file_path, gh_tools, llm, idx, len(file_paths))
                )

            # Process batch
            batch_results = await asyncio.gather(*batch_tasks)

            for result in batch_results:
                if result:
                    summaries.append(result)

            # Save progress every 50 files
            if (i + batch_size) % 50 == 0:
                print(f"\n  [SAVING] Progress checkpoint... ({len(summaries)} summaries so far)")
                with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
                    json.dump(summaries, f, indent=2)

    # 3. Save final results
    print(f"\n{'=' * 70}")
    print("Saving final results...")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(summaries, f, indent=2)

    file_size = OUTPUT_FILE.stat().st_size

    print(f"\n{'=' * 70}")
    print("[SUCCESS]")
    print(f"{'=' * 70}")
    print(f"Output file: {OUTPUT_FILE}")
    print(f"File size: {file_size:,} bytes ({file_size / 1024:.1f} KB)")
    print(f"Total files processed: {len(file_paths)}")
    print(f"Successful summaries: {len(summaries)}")
    print(f"Failed: {len(file_paths) - len(summaries)}")
    print(f"{'=' * 70}")

    return True


if __name__ == "__main__":
    print("\n[WARNING] This script will take approximately 40 minutes to complete.")
    print("It will process 1104+ files with Gemini Pro.\n")

    response = input("Continue? (yes/no): ").strip().lower()
    if response not in ["yes", "y"]:
        print("Aborted.")
        sys.exit(0)

    success = asyncio.run(rebuild_summaries())
    sys.exit(0 if success else 1)
