# Copyright (c) 2025-2026 Telomere LLC. All rights reserved.
# Proprietary and confidential. See LICENSE file in the project root.

from __future__ import annotations

import asyncio
import re
from typing import Optional

from agents.base_agent import BaseAgent
from config.settings import settings
from app_logging.activity_logger import ActivityLogger
from mcp_client.client_factory import filter_github_tools, filter_jira_tools, get_mcp_client, get_pr_mcp_client
from prompts.pr_composer_prompt import PR_TITLE_SYSTEM
from schemas.pr import PRCompositionResult, PRStatus
from schemas.workflow_state import WorkflowPhase, WorkflowState
from utils.mcp_helpers import find_tool, unwrap_tool_result

logger = ActivityLogger("pr_composer_agent")

AI_DISCLAIMER = """
---
> ⚠️ **This PR was generated by AI (Claude via AWS Bedrock) and requires thorough human review
> before merging. Verify all logic, test coverage, and edge cases independently.**
>
> _Generated by [Artoo](https://github.com/Telomere-techsupp/SDLCWorker) — by Telomere LLC_
> _© 2025-2026 Telomere LLC. All rights reserved._
""".strip()


def _build_pr_body(state: dict) -> str:
    ticket_id = state.get("ticket_id", "")
    ticket = state.get("ticket_context")
    plan = state.get("implementation_plan")
    code = state.get("code_proposal")
    tests = state.get("test_suggestions")

    parts = [f"## {ticket_id}: {ticket.title if ticket else 'AI-Generated PR'}", ""]

    # Jira link
    if settings.jira_url and ticket_id:
        parts += [
            f"**Jira Ticket:** [{ticket_id}]({settings.jira_url}/browse/{ticket_id})", ""
        ]

    # Summary
    if plan:
        parts += ["## Summary", plan.summary, ""]

    # Implementation Plan
    if plan and plan.implementation_steps:
        parts += ["## Implementation Plan", ""]
        for step in plan.implementation_steps:
            parts.append(
                f"**Step {step.step_number}: {step.title}**  "
                f"\n{step.description}"
                + (
                    f"\nFiles: `{'`, `'.join(step.affected_files)}`"
                    if step.affected_files
                    else ""
                )
            )
            parts.append("")

        if plan.risk_level:
            parts.append(f"**Risk Level:** {plan.risk_level.value.upper()} — {plan.risk_rationale}")
        if plan.breaking_changes:
            parts.append("⚠️ **Breaking Changes: YES**")
        if plan.database_migrations_required:
            parts.append("⚠️ **Database Migrations Required: YES**")
        if plan.deployment_considerations:
            parts.append("\n**Deployment Notes:**")
            for note in plan.deployment_considerations:
                parts.append(f"- {note}")
        parts.append("")

    # Code Changes Summary
    if code and code.file_changes:
        parts += ["## Proposed Code Changes", ""]
        for fc in code.file_changes:
            parts.append(f"### `{fc.file_path}` ({fc.change_type.value})")
            parts.append(fc.rationale)
            if fc.proposed_content:
                lang = _detect_lang(fc.file_path)
                parts.append(f"```{lang}")
                parts.append(fc.proposed_content[:2000])
                if len(fc.proposed_content) > 2000:
                    parts.append("... (truncated — see full diff in files)")
                parts.append("```")
            parts.append("")

        if code.new_dependencies:
            parts.append("**New Dependencies:**")
            for dep in code.new_dependencies:
                parts.append(f"- `{dep}`")
            parts.append("")

    # Test Suggestions
    if tests and tests.test_cases:
        parts += ["## Test Suggestions", ""]
        parts.append(f"Framework: `{tests.framework}`")
        parts.append("")
        for tc in tests.test_cases[:10]:
            edge = " *(edge case)*" if tc.edge_case else ""
            parts.append(f"- **{tc.test_name}**{edge} — {tc.description}")
        if len(tests.test_cases) > 10:
            parts.append(f"- _(+{len(tests.test_cases) - 10} more test cases)_")
        parts.append("")

    # Confluence Documentation References
    confluence = state.get("confluence_context")
    if confluence and confluence.pages_found:
        parts += ["## Confluence Documentation References", ""]
        for page in confluence.pages_found:
            parts.append(f"- [{page.title}]({page.url}) — {page.relevance_reason}")
        parts.append("")
        if confluence.doc_update_suggestions:
            parts += ["**Suggested Documentation Updates:**", ""]
            for suggestion in confluence.doc_update_suggestions:
                parts.append(f"- {suggestion}")
            parts.append("")

    # Confidence scores
    confidence_items = []
    if plan:
        confidence_items.append(f"Plan: {plan.confidence_score:.0%}")
    if code:
        confidence_items.append(f"Code: {code.confidence_score:.0%}")
    if tests:
        confidence_items.append(f"Tests: {tests.confidence_score:.0%}")
    if confidence_items:
        parts += ["## AI Confidence Scores", ", ".join(confidence_items), ""]

    parts.append(AI_DISCLAIMER)
    return "\n".join(parts)


def _detect_lang(file_path: str) -> str:
    ext_map = {
        ".py": "python", ".js": "javascript", ".ts": "typescript",
        ".go": "go", ".java": "java", ".rb": "ruby", ".rs": "rust",
        ".sh": "bash", ".yml": "yaml", ".yaml": "yaml", ".json": "json",
        ".tf": "hcl", ".sql": "sql",
    }
    for ext, lang in ext_map.items():
        if file_path.endswith(ext):
            return lang
    return ""


async def _create_branch(tools: list, owner: str, repo: str, branch_name: str, base_branch: str) -> bool:
    """Create a new branch from base_branch."""
    get_branch = find_tool(tools, "get_branch") or find_tool(tools, "branch", "get")
    create_branch = find_tool(tools, "create_branch")

    if not create_branch:
        logger.warning("github_create_branch_tool_not_found")
        return False

    try:
        base_sha = ""
        if get_branch:
            branch_data = await get_branch.ainvoke({"owner": owner, "repo": repo, "branch": base_branch})
            base_sha = branch_data.get("commit", {}).get("sha", "") if isinstance(branch_data, dict) else ""

        kwargs = {"owner": owner, "repo": repo, "branch": branch_name}
        if base_sha:
            kwargs["from_branch"] = base_branch
        await create_branch.ainvoke(kwargs)
        return True
    except Exception as exc:
        err_str = str(exc)
        if "already exists" in err_str.lower() or "reference already exists" in err_str.lower():
            logger.info("github_branch_already_exists", branch=branch_name)
            return True
        logger.warning("github_create_branch_failed", error=err_str)
        return False


async def _push_implementation_file(
    tools: list,
    owner: str,
    repo: str,
    branch_name: str,
    ticket_id: str,
    pr_body: str,
) -> None:
    """Push an IMPLEMENTATION_PLAN.md file to the branch."""
    file_path = f"ai_proposals/{ticket_id}/IMPLEMENTATION_PLAN.md"
    commit_message = f"chore({ticket_id}): add AI-generated implementation plan"

    # Prefer push_files (accepts raw text content directly)
    push_tool = find_tool(tools, "push_files")
    create_tool = find_tool(tools, "create_or_update_file")

    try:
        if push_tool:
            await push_tool.ainvoke({
                "owner": owner,
                "repo": repo,
                "branch": branch_name,
                "message": commit_message,
                "files": [{"path": file_path, "content": pr_body}],
            })
        elif create_tool:
            # The MCP GitHub server's create_or_update_file accepts plain text
            # and handles base64 encoding internally — do NOT encode here
            await create_tool.ainvoke({
                "owner": owner,
                "repo": repo,
                "path": file_path,
                "message": commit_message,
                "content": pr_body,
                "branch": branch_name,
            })
        else:
            logger.warning("github_push_file_tool_not_found")
    except Exception as exc:
        logger.warning("github_push_file_failed", error=str(exc))


async def _find_existing_pr(tools: list, owner: str, repo: str, branch_name: str) -> Optional[dict]:
    """Find an existing open PR for the given head branch."""
    list_prs = find_tool(tools, "list_pull_requests")
    if not list_prs:
        logger.warning("github_list_pull_requests_tool_not_found")
        return None

    try:
        raw = await list_prs.ainvoke({
            "owner": owner,
            "repo": repo,
            "state": "open",
            "head": f"{owner}:{branch_name}",
        })
        result = unwrap_tool_result(raw)
        # Result may be a list directly or wrapped in a key
        prs = result if isinstance(result, list) else result.get("pull_requests", result.get("items", []))
        if prs:
            return prs[0] if isinstance(prs, list) else None
    except Exception as exc:
        logger.warning("github_list_prs_failed", error=str(exc))
    return None


async def _update_pull_request(tools: list, owner: str, repo: str, pr_number: int, title: str, body: str) -> Optional[dict]:
    """Update an existing PR's title and body."""
    update_pr = find_tool(tools, "update_pull_request")
    if not update_pr:
        return None
    try:
        raw = await update_pr.ainvoke({
            "owner": owner,
            "repo": repo,
            "pull_number": pr_number,
            "title": title,
            "body": body,
        })
        return unwrap_tool_result(raw)
    except Exception as exc:
        logger.warning("github_update_pr_failed", error=str(exc))
        return None


async def _create_pull_request(
    tools: list,
    owner: str,
    repo: str,
    title: str,
    body: str,
    head_branch: str,
    base_branch: str,
    draft: bool,
    reviewers: list[str],
) -> dict:
    create_pr = find_tool(tools, "create_pull_request")
    if not create_pr:
        raise RuntimeError("create_pull_request tool not found in GitHub MCP")

    try:
        raw = await create_pr.ainvoke({
            "owner": owner,
            "repo": repo,
            "title": title,
            "body": body,
            "head": head_branch,
            "base": base_branch,
            "draft": draft,
        })
        return unwrap_tool_result(raw)
    except Exception as exc:
        err_str = str(exc)
        # Handle duplicate PR — GitHub returns 422 when a PR already exists for this branch
        if "422" in err_str or "already exists" in err_str.lower():
            logger.info("github_pr_already_exists_finding_existing", branch=head_branch)
            existing = await _find_existing_pr(tools, owner, repo, head_branch)
            if existing:
                pr_number = existing.get("number")
                logger.info("github_existing_pr_found", pr_number=pr_number)
                # Update the existing PR with fresh content
                await _update_pull_request(tools, owner, repo, pr_number, title, body)
                return existing
            # Could not find it — re-raise original
        raise


async def _transition_jira_ticket(ticket_id: str, target_status_name: str = "In Review") -> bool:
    """Transition a Jira ticket to the given status by finding the matching transition."""
    try:
        async with get_mcp_client() as client:
            all_tools = await client.get_tools()
            jira_tools = filter_jira_tools(all_tools)

            # Get available transitions
            get_transitions = find_tool(jira_tools, "jira_get_transitions") or find_tool(jira_tools, "transitions")
            if not get_transitions:
                logger.warning("jira_get_transitions_tool_not_found")
                return False

            raw = await get_transitions.ainvoke({"issue_key": ticket_id})
            transitions_data = unwrap_tool_result(raw)
            transitions = (
                transitions_data
                if isinstance(transitions_data, list)
                else transitions_data.get("transitions", [])
            )

            # Find a transition whose name contains our target (case-insensitive)
            # Fallback order: "In Review" → "In Progress" → "Done"
            candidates = [target_status_name, "In Review", "In Progress", "Done"]
            chosen_transition = None
            for candidate in candidates:
                for t in transitions:
                    name = (t.get("name") or t.get("to", {}).get("name", "")).lower()
                    if candidate.lower() in name:
                        chosen_transition = t
                        break
                if chosen_transition:
                    break

            if not chosen_transition:
                logger.warning(
                    "jira_no_matching_transition",
                    ticket_id=ticket_id,
                    available=[t.get("name") for t in transitions],
                )
                return False

            transition_id = chosen_transition.get("id")
            transition_name = chosen_transition.get("name")

            # Execute the transition
            do_transition = find_tool(jira_tools, "jira_transition_issue") or find_tool(jira_tools, "transition_issue")
            if not do_transition:
                logger.warning("jira_transition_issue_tool_not_found")
                return False

            await do_transition.ainvoke({
                "issue_key": ticket_id,
                "transition_id": str(transition_id),
            })
            logger.info("jira_ticket_transitioned", ticket_id=ticket_id, transition=transition_name)
            return True

    except Exception as exc:
        logger.warning("jira_transition_failed", ticket_id=ticket_id, error=str(exc))
        return False


async def _post_jira_pr_comment(ticket_id: str, pr_url: str, pr_number: Optional[int], branch_name: str) -> bool:
    """Post a comment on the Jira ticket with the PR link."""
    try:
        async with get_mcp_client() as client:
            all_tools = await client.get_tools()
            jira_tools = filter_jira_tools(all_tools)

            add_comment = find_tool(jira_tools, "jira_add_comment") or find_tool(jira_tools, "add_comment")
            if not add_comment:
                logger.warning("jira_add_comment_tool_not_found")
                return False

            pr_ref = f"#{pr_number}" if pr_number else "draft"
            comment_body = (
                f"🤖 **Artoo** has processed this ticket and created a draft Pull Request.\n\n"
                f"**Pull Request:** [{pr_ref}]({pr_url})\n"
                f"**Branch:** `{branch_name}`\n\n"
                f"The PR includes:\n"
                f"- Implementation plan with step-by-step changes\n"
                f"- Proposed code diffs\n"
                f"- Test suggestions\n\n"
                f"_Please review the AI-generated proposal carefully before merging._"
            )

            await add_comment.ainvoke({
                "issue_key": ticket_id,
                "body": comment_body,
            })
            logger.info("jira_pr_comment_posted", ticket_id=ticket_id)
            return True

    except Exception as exc:
        logger.warning("jira_comment_failed", ticket_id=ticket_id, error=str(exc))
        return False


async def _do_create_pr(state: dict) -> PRCompositionResult:
    ticket_id = state["ticket_id"]
    ticket = state.get("ticket_context")

    # Use personal demo repo for PR creation if configured, else fall back to scout repo
    owner = settings.github_pr_repo_owner or settings.github_repo_owner
    repo = settings.github_pr_repo_name or settings.github_repo_name
    base_branch = settings.github_base_branch

    # Sanitise branch name
    safe_id = re.sub(r"[^a-zA-Z0-9_-]", "-", ticket_id).lower()
    branch_name = f"ai/{safe_id}"

    pr_title = f"feat({ticket_id}): {ticket.title[:50] if ticket else ticket_id} [AI]"
    pr_body = _build_pr_body(state)

    async with get_pr_mcp_client() as client:
        all_tools = await client.get_tools()
        gh_tools = filter_github_tools(all_tools)

        # Create branch
        branch_created = await _create_branch(gh_tools, owner, repo, branch_name, base_branch)

        # Push implementation plan file to branch
        if branch_created:
            await _push_implementation_file(gh_tools, owner, repo, branch_name, ticket_id, pr_body)

        # Create (or find/update) draft PR
        reviewers = settings.default_reviewers_list
        pr_data = await _create_pull_request(
            gh_tools, owner, repo,
            title=pr_title,
            body=pr_body,
            head_branch=branch_name if branch_created else base_branch,
            base_branch=base_branch,
            draft=True,
            reviewers=reviewers,
        )

    pr_url = pr_data.get("html_url") or pr_data.get("url")
    pr_number = pr_data.get("number")

    # Post Jira comment with PR link (suppressed when jira_read_only or dry_run)
    if pr_url and not settings.jira_read_only and not settings.dry_run:
        await _post_jira_pr_comment(ticket_id, pr_url, pr_number, branch_name)

    return PRCompositionResult(
        ticket_id=ticket_id,
        status=PRStatus.CREATED if pr_url else PRStatus.FAILED,
        pr_url=pr_url,
        pr_number=pr_number,
        branch_name=branch_name,
        base_branch=base_branch,
        pr_title=pr_title,
        pr_body=pr_body,
        draft=True,
        reviewers_requested=reviewers,
        jira_ticket_linked=bool(settings.jira_url),
        raw_mcp_output=pr_data,
    )


class PRComposerAgent(BaseAgent):
    def run(self, state: WorkflowState) -> dict:
        ticket_id = state["ticket_id"]
        run_id = state["run_id"]

        self.logger.info(
            "agent_node_entered",
            ticket_id=ticket_id,
            run_id=run_id,
            phase=WorkflowPhase.COMPOSING_PR,
        )

        if settings.dry_run:
            self.logger.info("dry_run_skip_pr_creation", ticket_id=ticket_id, run_id=run_id)
            pr_body = _build_pr_body(dict(state))
            return {
                "pr_result": PRCompositionResult(
                    ticket_id=ticket_id,
                    status=PRStatus.SKIPPED,
                    pr_title=f"[DRY RUN] {ticket_id}",
                    pr_body=pr_body,
                    draft=True,
                ),
                "current_phase": WorkflowPhase.COMPLETED,
            }

        try:
            pr_result = self.run_async(_do_create_pr(dict(state)))

            self.logger.info(
                "github_pr_created",
                ticket_id=ticket_id,
                run_id=run_id,
                pr_url=pr_result.pr_url,
                pr_number=pr_result.pr_number,
            )

            return {
                "pr_result": pr_result,
                "current_phase": WorkflowPhase.COMPLETED,
                "mcp_tool_calls": [{"tool": "github_create_pull_request", "pr_number": pr_result.pr_number}],
            }

        except Exception as exc:
            self.logger.error("github_pr_failed", exc=exc, ticket_id=ticket_id, run_id=run_id)
            return {
                "pr_result": PRCompositionResult(
                    ticket_id=ticket_id,
                    status=PRStatus.FAILED,
                    pr_title=f"[FAILED] {ticket_id}",
                    error_message=str(exc),
                ),
                "current_phase": WorkflowPhase.FAILED,
                "errors": [f"pr_composer: {exc}"],
            }


_agent = PRComposerAgent()


def pr_composer_node(state: WorkflowState) -> dict:
    return _agent.run(state)
